services:
  nginx:
    image: nginx-image:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net
    volumes:
      - /home/user/webserver/certs:/etc/letsencrypt

  apache:
    image: apache-image:latest
    networks:
      - net

networks:
  net:
    driver: bridge
