version: '3.8'

services:
  nginx:
    image: nginx-image:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - test
    volumes:
      - ./certs:/etc/letsencrypt

  apache:
    image: apache-image:latest
    networks:
      - test

networks:
  test:
    driver: bridge
